name: bullion
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  instabug_flutter: ^12.5.0

  #core
  stacked: ^3.4.1
  stacked_themes: ^0.3.12
  permission_handler: ^11.3.0

  #Firebase
  firebase_core: ^2.21.0
  firebase_analytics: ^10.6.3
  firebase_crashlytics: ^3.4.3
  firebase_dynamic_links: ^5.4.3
  firebase_remote_config: ^4.3.3
  onesignal_flutter: ^5.1.0

  #Http
  http: ^1.1.0

  #UI
  card_swiper: ^3.0.1
  smooth_page_indicator: ^1.1.0
  persistent_bottom_nav_bar_v2: ^4.2.8
  flutter_rating_bar: ^4.0.1
  dotted_border: ^2.1.0
  dotted_line: ^3.2.2
  photo_view: ^0.14.0

  #chart
  chart_sparkline: ^1.0.13
  syncfusion_flutter_charts: ^20.4.44

  #Payment
  flutter_braintree:
    git:
      url: https://github.com/santhoshvgts/flutter-braintree.git
      ref: 0.0.1+4

  app_tracking_transparency: ^2.0.4

  plaid_flutter: ^3.1.4
  credit_card_scanner: ^1.0.5

  #local
  shared_preferences: ^2.2.1
  event_taxi: ^1.0.0

  #Utils
  font_awesome_flutter: ^10.5.0
  feather_icons: ^1.2.0
  url_launcher: ^6.1.14
  uuid: ^4.0.0
  flutter_styled_toast: ^2.2.1
  package_info_plus: ^4.1.0
  device_info_plus: ^9.0.3
  auto_size_text: ^3.0.0
  flutter_cache_manager: ^3.3.1
  model_viewer_plus: ^1.7.0
  intl: ^0.18.1
  loading_animation_widget: ^1.2.0+4
  flutter_typeahead: ^4.8.0
  collection: ^1.17.2
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.3.0
  avoid_keyboard: ^0.3.0
  share_plus: ^7.2.1
  flutter_nfc_kit: ^3.4.2

  #html_utils
  flutter_widget_from_html: ^0.10.5+3
  flutter_linkify: ^6.0.0
  markdown: ^7.1.1
  webview_flutter: ^4.2.4

  #social_authentication
  firebase_auth: ^4.17.2
  google_sign_in: ^6.2.1


  vgts_plugin:
#    path: ../../vgts_plugin
    git:
      url: https://github.com/santhoshvgts/vgts_plugin.git
      ref: 1.0.0+12
  sentry_flutter: ^7.12.0
  uni_links: ^0.5.1

  #Analytics
  kochava_tracker: ^2.4.0
  flutter_spinkit: ^5.2.0
  gif_view: ^0.4.0
  flutter_riskified:
    git:
      url: https://github.com/santhoshvgts/flutter_riskified.git
      ref: 0.0.4
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/models/
    - assets/gif/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
