name: bullion
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #core
  stacked: ^3.4.1

  #Firebase
  firebase_core: ^2.15.1
  firebase_analytics: ^10.4.5
  firebase_crashlytics: ^3.3.5
  firebase_dynamic_links: ^5.3.5
  firebase_remote_config: ^4.2.5

  #Http
  http: ^1.1.0

  #UI
  card_swiper: ^3.0.1
  smooth_page_indicator: ^1.1.0

  #local
  shared_preferences: ^2.2.1
  event_taxi: ^1.0.0

  #Utils
  font_awesome_flutter: ^10.5.0
  url_launcher: ^6.1.14
  uuid: ^4.0.0
  flutter_styled_toast: ^2.2.1
  package_info_plus: ^4.1.0
  device_info_plus: ^9.0.3
  auto_size_text: ^3.0.0

  #html_utils
  flutter_widget_from_html: ^0.10.5+3
  flutter_linkify: ^6.0.0
  markdown: ^7.1.1
  webview_flutter: ^4.2.4

  vgts_plugin:
    git:
      url: https://github.com/santhoshvgts/vgts_plugin.git
      ref: "1.0.0+7"

  #Analytics
  kochava_tracker: ^2.4.0
#  flutter_riskified:
#    git:
#      url: https://github.com/santhoshvgts/flutter_riskified.git
#      ref: "0.0.3"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
