class ProductVariant {
  String? variantGroupName;
  List<Options>? options;

  ProductVariant({this.variantGroupName, this.options});

  ProductVariant.fromJson(Map<String, dynamic> json) {
    variantGroupName = json['varient_group_name'];
    if (json['options'] != null) {
      options = <Options>[];
      json['options'].forEach((v) {
        options!.add(Options.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data['varient_group_name'] = variantGroupName;
    if (options != null) {
      data['options'] = options!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Options {
  String? variantOptionName;
  String? targetUrl;
  bool? isSelected;
  String? variantName;

  Options(
      {this.variantOptionName,
        this.targetUrl,
        this.isSelected,
        this.variantName});

  Options.fromJson(Map<String, dynamic> json) {
    variantOptionName = json['variant_option_name'];
    targetUrl = json['target_url'];
    isSelected = json['is_selected'];
    variantName = json['variant_name'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data['variant_option_name'] = variantOptionName;
    data['target_url'] = targetUrl;
    data['is_selected'] = isSelected;
    data['variant_name'] = variantName;
    return data;
  }
}
class Autogenerated {
  List<ProductVariant>? productVariants;

  Autogenerated({this.productVariants});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['product_variants'] != null) {
      productVariants = <ProductVariant>[];
      json['product_variants'].forEach((v) {
        productVariants!.add(ProductVariant.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (productVariants != null) {
      data['product_variants'] =
          productVariants!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}